### ISSUE TITLE
Filter: Drop-Shadow?

### ISSUE THREAD

**Issue by jjjrmy** [jamessessford/tailwindcss-pulse#1]
Is it possible to do this with Filter: Drop-shadow so you can use this on SVGs and Icons?
(Think FontAwesome)

Thanks

**Comment by jamessessford** [comment]
Awesome shout! Let me take a look at this

**Comment by jjjrmy** [comment]
> Awesome shout! Let me take a look at this

I tried it out and I don't think it's possible because Filter DropShadow doesn't have the same properties.
Maybe you have a better idea though.

**Comment by jamessessford** [comment]
Hey bud,

I've just pushed an update to generate utilities that use a filter shadow instead.

They're generated as shadow-pulse-<color>

I'll close this off but feel free to reopen if needed!
